base_to_MIRA = {
    "Filename":                 "tufts:filename",
    "Has_Model":                "model:hasModel",
    "MIRA_ID":                  "tufts:id",
    "Member_Of":                "tufts:memberOf",
    "Type":                     "dc:type",
    "Abstract":                 "dc:abstract",
    "Alternative_Title":        "dc:alternative",
    "Bibliographic_Citation":   "dc:bibliographicCitation",
    "Contributor":              "dc11:contributor",
    "Corporate_Name":           "mads:CorporateName",
    "Creator":                  "dc11:creator",
    "Creator_Department":       "tufts:creator_department",
    "Description":              "dc11:description",
    "Displays_In":              "tufts:displays_in",
    "DOI":                      "bibframe:doi",
    "Embargo_Release_Date":     "tufts:embargo_release_date",
    "Extent":                   "dc:extent",
    "Format":                   "dc:format",
    "Genre":                    "mads:GenreForm",
    "Geographic_Name":          "tufts:geog_name",
    "Internal_Note":            "tufts:internal_note",
    "ISBN":                     "bibframe:isbn",
    "Is_Part_Of":               "dc:isPartOf",
    "OCLC_No":                  "tufts:oclc",
    "Personal_Name":            "mads:PersonalName",
    "Primary_Date":             "dc11:date",
    "QR_Note":                  "tufts:qr_note",
    "License":                  "edm:rights",
    "Rights_Note":              "dc11:rights",
    "Source":                   "dc:source",
    "Spatial":                  "dc:spatial",
    "Steward":                  "tufts:steward",
    "Subject":                  "dc11:subject",
    "Table_Of_Contents":        "dc:tableOfContents",
    "Temporal":                 "dc:temporal",
    "Thesis_Type":              "bf2:dissertation",
    "Title":                    "dc:title",
    "Visibility":               "tufts:visibility",
    "Publisher":                "dc11:publisher"
    }

normalize_excel = {
    "Accession":                "Filename",
    "Alternative Title":        "Alternative_Title",
    "Contributors":             "Contributor",
    "Date Created":             "Primary_Date",
    "personalNames":            "Personal_Name",
    "Personal Names":           "Personal_Name",
    "corporateNames":           "Corporate_Name",
    "Corporate Names":          "Corporate_Name",
    "geographicTerms":          "Geographic_Name",
    "Geographic Names":         "Geographic_Name",
    "Century":                  "Temporal",
    "Embargo":                  "Embargo_Release_Date",
    "Member Of":                "Member_Of",
    "Has Model":                "Has_Model",
    "Corporate Name":           "Corporate_Name",
    "Creator Department":       "Creator_Department",
    "Mira ID":                  "MIRA_ID",
    "Member of":                "Member_Of",
    "Alternative Title":        "Alternative_Title",
    "Bibliographic Citation":   "Bibliographic_Citation",
    "Corporate_Name":           "Corporate_Name",
    "Creator Department":       "Creator_Department",
    "Displays In":              "Displays_In",
    "Displays in":              "Displays_In",
    "Embargo Release Date":     "Embargo_Release_Date",
    "Embargo Date":             "Embargo_Release_Date",
    "Geographic Name":          "Geographic_Name",
    "Internal Note":            "Internal_Note",
    "Is Part Of":               "Is_Part_Of",
    "Is Part of":               "Is_Part_Of",
    "Personal Name":            "Personal_Name",
    "Primary Date":             "Primary_Date",
    "QR Note":                  "QR_Note",
    "Rights Note":              "Rights_Note",
    "TableOfContents":          "Table_Of_Contents",
    "Table of Contents":        "Table_Of_Contents",
    "Table Of Contents":        "Table_Of_Contents",
    "Thesis Type":              "Thesis_Type"
    }
